### ISSUE TITLE
Fix Drag and Drop

### ISSUE THREAD

**Issue by bsrmdn** [Mutuharjo-Game-Development/EducationGame#11]
Merubah fitur drag and drop agar dapat mengetahui benar atau salah letak dari object yang di drag

**Comment by ant1po1e** [comment]
afkh sudah
@bsrmdn

**Comment by bsrmdn** [comment]
> afkh sudah
> @bsrmdn 
> 

sdh

**Comment by ant1po1e** [comment]
baiklah

**Comment by ant1po1e** [comment]
lah pr nya udah?
